services:
  configserver:
    image: "javi314/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sofibank
  accounts:
    image: "javi314/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sofibank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SRING_PROFILES_ACTIVE: default
  loans:
    image: "javi314/loans-ms"
    container_name: "javi314/loans:s6"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sofibank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SRING_PROFILES_ACTIVE: default
  cards:
    image: "javi314/cards:s6"
    container_name: accounts-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sofibank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SRING_PROFILES_ACTIVE: default
networks:
  sofibank:
    driver: "bridge"