server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    imports:
      - "application_qa.yml"
      - "application_prod.yml"
    profiles:
      active: "prod"

build:
  info: "3.0"

loans:
  contact:
    message: "Welcome to SofiBank accounts related dev APIs"
    contactDetails:
      name: "Javi - Product Owner"
      email: "javie@sofibank.com"
    onCallSupport:
      -(555)555-1289 
      -(555)555-8921
